### ISSUE TITLE
Doesn't exit from OPS

### ISSUE THREAD

**Issue by Haroenv** [Haroenv/shuttle-command#7]
* -004 *200 /006 doesn't exit
* -003 *438 /439 doesn't exit

**Comment by gaetanverbrugghe** [comment]
-003 *438 /439 does exit: issue fixed.

**Comment by Haroenv** [comment]
So the other one is still a problem? Thanks a lot by the way @gatanverbrugghe

**Comment by gaetanverbrugghe** [comment]
The other one isn't a problem for me.

**Comment by Haroenv** [comment]
Can you show a screenshot that it works? I'll close this issue then

**Comment by gaetanverbrugghe** [comment]
![schermafdruk van 2016-11-25 19 50 26](https://cloud.githubusercontent.com/assets/22528030/20633618/1daf1a0c-b349-11e6-8e93-518471eb59bc.png)

**Comment by Haroenv** [comment]
Thanks a lot! Keep it up
